DROP DATABASE IF EXISTS mood_db;
CREATE DATABASE mood_db;

use mood_db;

CREATE TABLE notes (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    emotion INT,
    title VARCHAR(100),
    note VARCHAR(400),
    user VARCHAR(50),
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE userSchema (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL
);