INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 5, 'Pokemon', 'Charizard hit 9000 today', 'Bicwik', '2021-03-05 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 1, 'Pokemon2', 'Omg mewtwo', 'Bicwik', '2021-02-22 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 2, 'Pokemon3', 'Can not find', 'Bicwik', '2021-03-03 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 5, 'Pokemon4', 'Got em', 'Bicwik', '2021-03-05 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 4, 'Jane Eyre', '“I am no bird; and no net ensnares me: I am a free human being with an independent will, which I now exert to leave you.”', 'Bicwik', '2021-03-05 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 5, 'A Tale of Two Cities', '“It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.” — Charles Dickens, A Tale of Two Cities', 'Bicwik', '2021-03-06 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 3, 'To Kill a Mockingbird', '“I wanted you to see what real courage is, instead of getting the idea that courage is a man with a gun in his hand. It’s when you know you’re licked before you begin but you begin anyway and you see it through no matter what. You rarely win, but sometimes you do.” — Harper Lee', 'Bicwik', '2021-03-07 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 3, 'East of Eden', '“A man, after he has brushed off the dust and chips of his life, will have left only the hard, clean questions: Was it good or was it evil? Have I done well — or ill?” — John Steinbeck', 'Bicwik', '2020-07-06 15:27:56');
INSERT INTO notes ( emotion, title, note, user, time ) VALUES ( 5, 'Looking for Alaska', '“The only way out of the labyrinth of suffering is to forgive.” ― John Green', 'Bicwik', '2020-08-06 15:27:56');
